development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password: password
  port: 2222


test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myapp_test
  pool: 5
  username: piproj
  password: piproj

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myapp_development
  pool: 5
  username: piproj
  password: piproj
